/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentRouteImport } from './routes/student'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentHistoryRouteImport } from './routes/student.history'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentRecallRouteImport } from './routes/student.recall'
import { Route as StudentTestsRouteImport } from './routes/student.tests'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherReportsRouteImport } from './routes/teacher.reports'
import { Route as TeacherSettingsRouteImport } from './routes/teacher.settings'
import { Route as TeacherTestsRouteImport } from './routes/teacher.tests'
import { Route as TeacherStudentsIndexRouteImport } from './routes/teacher.students.index'
import { Route as TeacherStudentsStudentIdRouteImport } from './routes/teacher.students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHistoryRoute = StudentHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRecallRoute = StudentRecallRouteImport.update({
  id: '/recall',
  path: '/recall',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTestsRoute = StudentTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherSettingsRoute = TeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherTestsRoute = TeacherTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherStudentsIndexRoute = TeacherStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherStudentsStudentIdRoute =
  TeacherStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => TeacherRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/history': typeof StudentHistoryRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/recall': typeof StudentRecallRoute
  '/student/tests': typeof StudentTestsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/tests': typeof TeacherTestsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/teacher/students/': typeof TeacherStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/recall': typeof StudentRecallRoute
  '/student/tests': typeof StudentTestsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/tests': typeof TeacherTestsRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/teacher/students': typeof TeacherStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/history': typeof StudentHistoryRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/recall': typeof StudentRecallRoute
  '/student/tests': typeof StudentTestsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/tests': typeof TeacherTestsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/teacher/students/': typeof TeacherStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/student'
    | '/teacher'
    | '/student/history'
    | '/student/profile'
    | '/student/recall'
    | '/student/tests'
    | '/teacher/reports'
    | '/teacher/settings'
    | '/teacher/tests'
    | '/student/'
    | '/teacher/'
    | '/teacher/students/$studentId'
    | '/teacher/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/student/history'
    | '/student/profile'
    | '/student/recall'
    | '/student/tests'
    | '/teacher/reports'
    | '/teacher/settings'
    | '/teacher/tests'
    | '/student'
    | '/teacher'
    | '/teacher/students/$studentId'
    | '/teacher/students'
  id:
    | '__root__'
    | '/'
    | '/student'
    | '/teacher'
    | '/student/history'
    | '/student/profile'
    | '/student/recall'
    | '/student/tests'
    | '/teacher/reports'
    | '/teacher/settings'
    | '/teacher/tests'
    | '/student/'
    | '/teacher/'
    | '/teacher/students/$studentId'
    | '/teacher/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/history': {
      id: '/student/history'
      path: '/history'
      fullPath: '/student/history'
      preLoaderRoute: typeof StudentHistoryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/recall': {
      id: '/student/recall'
      path: '/recall'
      fullPath: '/student/recall'
      preLoaderRoute: typeof StudentRecallRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/tests': {
      id: '/student/tests'
      path: '/tests'
      fullPath: '/student/tests'
      preLoaderRoute: typeof StudentTestsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/settings': {
      id: '/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof TeacherSettingsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/tests': {
      id: '/teacher/tests'
      path: '/tests'
      fullPath: '/teacher/tests'
      preLoaderRoute: typeof TeacherTestsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/students/': {
      id: '/teacher/students/'
      path: '/students'
      fullPath: '/teacher/students/'
      preLoaderRoute: typeof TeacherStudentsIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/students/$studentId': {
      id: '/teacher/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/teacher/students/$studentId'
      preLoaderRoute: typeof TeacherStudentsStudentIdRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface StudentRouteChildren {
  StudentHistoryRoute: typeof StudentHistoryRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentRecallRoute: typeof StudentRecallRoute
  StudentTestsRoute: typeof StudentTestsRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentHistoryRoute: StudentHistoryRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentRecallRoute: StudentRecallRoute,
  StudentTestsRoute: StudentTestsRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherSettingsRoute: typeof TeacherSettingsRoute
  TeacherTestsRoute: typeof TeacherTestsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherStudentsStudentIdRoute: typeof TeacherStudentsStudentIdRoute
  TeacherStudentsIndexRoute: typeof TeacherStudentsIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherSettingsRoute: TeacherSettingsRoute,
  TeacherTestsRoute: TeacherTestsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherStudentsStudentIdRoute: TeacherStudentsStudentIdRoute,
  TeacherStudentsIndexRoute: TeacherStudentsIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
